### ISSUE TITLE
Nothing happens with correct settings for webpack 2

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [postcss/postcss-loader#162] opened 2017-01-13 08:07 UTC
Hi guys,

Sorry for creating another topic, but it is getting crazy, just cannot do nothing.

So postcss-loader does not trigger anything, thus my files remain unprocessed. I suppose it just does not enter any plugins section.

`config/webpack-base.js`
```js

const { resolve } = require('path');
const webpack = require('webpack');

module.exports = {
  entry: [
    // activate HMR for React
    'react-hot-loader/patch',

    // bundle the client for webpack-dev-server
    // and connect to the provided endpoint
    // 'webpack-dev-server/client?http://localhost:8080',
    'webpack-hot-middleware/client',

    // bundle the client for hot reloading
    // only- means to only hot reload for successful updates
    'webpack/hot/only-dev-server',


    // the entry point of our app
    './src/index.js'
  ],
  output: {
    // the output bundle
    filename: 'main.js',

    path: resolve(__dirname, '../', 'app', 'dist'),

    // necessary for HMR to know where to load the hot update chunks
    publicPath: '/'
  },

  context: resolve(__dirname, '../', 'app'),

  devtool: 'cheap-module-source-map',

  devServer: {
    // enable HMR on the server
    hot: true,

    // match the output path
    contentBase: resolve(__dirname, '../', 'app', 'dist'),

    // match the output `publicPath`
    publicPath: '/'
  },

  module: {
    rules: [
      {
        test: /\.jsx?$/,
        enforce: 'pre',
        exclude: /node_modules/,
        use: [
          'eslint-loader'
        ]
      },
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [
          'babel-loader'
        ]
      },
      {
        test: /\.css$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'style-loader',
            options: {
              sourceMap: true
            }
          },
          {
            loader: 'css-loader',
            options: {
              modules: true,
              importLoaders: 1,
              localIdentName: '[path]___[name]__[local]___[hash:base64:5]'
            }
          },
          {
            loader: 'postcss-loader'
          }
        ],
      },
    ]
  },

  resolve: {
    extensions: ['.jsx', '.js', '.json', '.css'],
    alias: {
      css: resolve(__dirname, '../', 'app', 'src', 'styles')
    }
  },

  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),

    // enable HMR globally
    new webpack.HotModuleReplacementPlugin(),

    // prints more readable module names in the browser console on HMR updates
    new webpack.NamedModulesPlugin(),
  ]
};

```

Currently I came to this `postcss.config.js`
```js
// module.exports = {
//   plugins: [
//     require('postcss-cssnext')({})
//   ]
// };

module.exports = (ctx) => {
  "use strict";

  console.log('ctx: ', ctx);

  return ({
    plugins: {
      'postcss-plugin': ctx.plugin
    }
  });
};
```

I have tried inline options for loader.
I have tried function instead of simple object export.
I have tried run after require.
I have tried do not run after require.
I have tried to move around the config file.

I have tried every option, which I saw for `postcss.config.js` and it leaves file unprocessed.

How could I debug what's happening and make loader to see the config?

Thanks.

**Comment by ai** [comment] 2017-01-13 13:46
Could you remove all webpack plugins and try again?

**Comment by michael-ciniawsky** [comment] 2017-01-13 23:18
@AlexanderTserkovniy 

**webpack.config.js**

- config.resolve may cause problems, please use it when a simple setup works to be sure it's not another problem

```diff
resolve: {
-  extensions: ['.jsx', '.js', '.json', '.css'],
+ extensions: ['.jsx', '.js', '.json'],
-  alias: {
-     css: resolve(__dirname, '../', 'app', 'src', 'styles')
-  }
}
```

- use a String with the loader name instead of an Object, it should work in both ways, but for now I can personally confirm that the string approach definitely works :)

```js
....
- {
-   loader: 'postcss-loader'
- }
+ 'postcss-loader'
....
```

**postcss.config.js**

- test with one plugin without any side effects (e.g relying on external resources like @import)

**postcss.config.js**
```js
module.exports = (ctx) => ({
   plugins: {
     'postcss-nested': {}
   }
}) 
```

If there is any bug occuring when you raise config complexity, please make a test repo so I can reproduce and fix.

**Comment by AlexanderTserkovniy** [comment] 2017-01-16 19:58
@michael-ciniawsky nope, does not work either. Should probably create a repo.

**Comment by AlexanderTserkovniy** [comment] 2017-01-16 20:36
Seems like it started working with latest version of loader as well as following `postcss.config.js`:

```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
  },
};
```

**Comment by AlexYankee** [comment] 2017-01-16 21:46
Got stuck with this one as well. After digging around a while i narrowed it down - style-loader.
While generating JS source it uses loaderUtils.stringify to stringify loader context. Having this done further loaders will loose all the options, defined locally, except of query params (can be noticed in webpack output btw):

`./~/css-loader?{"test":"1"}!./~/postcss-loader?{}!./src/style/style.css`

notice how style-loader passes call down to postcss-loader supplying it with empty query obj.
The workaround is to pass config file name to postcss-loader via query param:

```
use: [
    'style-loader',
    'css-loader',
    'postcss-loader?config=postcss.config.js'
]
```

then delegate all the magic to the config file. As it turned out config file can export function, which will be invoked with webpack env variable first argument - useful if one wants to use postcss-smart-import

```
module.exports = function(webpack) {
  return {
    plugins: [
        ...
        atImport({
          addDependencyTo: webpack
        }),
```

**Comment by michael-ciniawsky** [comment] 2017-01-17 07:52
> Seems like it started working with latest version of loader as well as following postcss.config.js:

@AlexanderTserkovniy We can close 😛 ?

@AlexYankee Can you elaborate on the `style-loader` issue a bit more please ? :)

```diff
- const atImport = require('postcss-smart-import')
+ const atImport = require('postcss-import')

// postcss-import  >= v9 + postcss-loader adds @import automatically to webpack now
// webpack -> ctx.webpack 

- module.exports = function(webpack) {
+ module.exports = (ctx)  => ({
- return {
    plugins: [
        ...
        atImport({
-        addDependencyTo: webpack
+        addDependencyTo: ctx.webpack
        }),
```

```js
module.exports = (ctx) => ({
   plugins: [
      atImport()
   ]
})
```

**Comment by AlexYankee** [comment] 2017-01-17 08:11
@michael-ciniawsky keeping it brief - it's impossible to pass options to postcss-loader via in-place loader configuration while using style-loader, so your Webpack 2 options example will not work:
```
 [
   'style-loader',
   'css-loader',
    {
      loader: 'postcss-loader',
      // Options will have no effect
      options: {
        plugins: function () {
          return [
            require('precss'),
            require('autoprefixer')
          ];
        }
      }
    }
]
```

**Comment by michael-ciniawsky** [comment] 2017-01-17 08:32
@AlexYankee Can you try the following please, I currently on fixing that, but haven't found time to test with `extract-text-webpack-plugin` and was aware of `style-loader` until now. In general there is a problem with 'advanced' options in webpack since `rc`. Using functions and 'require()` in loader options  doesn't work/parsed without an identifier anymore...I'm currently asking why and if thats the final behavior, if so I will update the docs soon.

```js
 [
   'style-loader',
   'css-loader',
    {
      loader: 'postcss-loader',
      options: {
        ident: 'postcss', // <---
        plugins: function () {
          return [
            require('precss'),
            require('autoprefixer')
          ];
        }
      }
    }
]
```

**Comment by AlexYankee** [comment] 2017-01-17 08:33
@michael-ciniawsky Will do! Thanks for you all you hard work, postcss delivers!

**Comment by AlexanderTserkovniy** [comment] 2017-01-17 08:42
Thanks @michael-ciniawsky as soon as you figure out everything else, you can close the ticket.

**Comment by michael-ciniawsky** [comment] 2017-01-17 09:58
@AlexanderTserkovniy Will do, on it already, but for you it works with your setup atm? If close please and of course feel free to reopen anytime if an error occurs :)

**Comment by AlexanderTserkovniy** [comment] 2017-01-17 10:29
Yes it works, here are some details:

`postcss.config.js`
```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
    'postcss-nested': {}
  },
};
```

`package.json`
```
"dependencies": {
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "devDependencies": {
    "babel-core": "^6.13.2",
    "babel-loader": "^6.2.10",
    "babel-preset-es2015": "^6.13.2",
    "babel-preset-react": "^6.11.1",
    "babel-preset-stage-2": "^6.13.0",
    "css-loader": "^0.23.1",
    "extract-text-webpack-plugin": "^2.0.0-beta.5",
    "postcss-cssnext": "^2.9.0",
    "postcss-import": "^9.1.0",
    "postcss-loader": "^1.2.2",
    "postcss-nested": "^1.0.0",
    "react-css-modules": "^4.1.0",
    "react-hot-loader": "^3.0.0-beta.6",
    "style-loader": "^0.13.1",
    "webpack": "^2.2.0-rc.7",
    "webpack-dev-server": "^2.2.0-rc.0"
  }
```

Full `webpack.config.js` in case:
```
const {resolve} = require('path');
const webpack = require('webpack');

module.exports = {
  context: resolve(__dirname, 'src'),
  entry: [
    'react-hot-loader/patch',
    // activate HMR for React

    'webpack-dev-server/client?http://localhost:8080',
    // bundle the client for webpack-dev-server
    // and connect to the provided endpoint

    'webpack/hot/only-dev-server',
    // bundle the client for hot reloading
    // only- means to only hot reload for successful updates

    resolve(__dirname, 'index.js')
  ],
  output: {
    path: resolve(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/'
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        use: [
          'babel-loader',
        ],
        exclude: /node_modules/
      },
      {
        test: /\.css$/,
        use: [
          'style-loader',
          'css-loader?sourceMap&modules&importLoaders=1&localIdentName=[path]___[name]__[local]___[hash:base64:5]',
          'postcss-loader'
        ],
      }
    ]
  },
  resolve: {
    extensions: ['.js', '.json', '.jsx']
  },
  devServer: {
    hot: true,
    // enable HMR on the server

    contentBase: resolve(__dirname, 'dist'),
    // match the output path

    publicPath: '/'
    // match the output `publicPath`
  },
  plugins: [
    new webpack.HotModuleReplacementPlugin(),
    // enable HMR globally

    new webpack.NamedModulesPlugin(),
    // prints more readable module names in the browser console on HMR updates
  ],
  devtool: 'cheap-module-eval-source-map'
};
```

**Comment by michael-ciniawsky** [comment] 2017-01-17 10:46
@AlexanderTserkovniy  👍 

**postcss.config.js**

```js
module.exports = {
  plugins: {
    'postcss-import': {},
    'postcss-cssnext': {
      browsers: ['last 2 versions', '> 5%'],
    },
    'postcss-nested': {} // unnecessary, nesting is already supported by cssnext
  },
};
```

[CSSNext](https://github.com/MoOx/postcss-cssnext/blob/master/package.json#L47)

Everything else seems to be pretty sane 😛

**Closed by michael-ciniawsky** 2017-01-17 10:46 UTC

**Comment by csmosx** [comment] 2017-01-19 20:01
@michael-ciniawsky thank you for the `options.ident = 'postcss'` tip.
It fixed the "No PostCSS Config found" error I couldn't figure out.

You said:

> I'm currently asking why and if thats the final behavior, if so I will update the docs soon.

I'm interested in that too.
Did you ask somewhere on Github? If so, could you provide the link?

Thanks.

**Comment by michael-ciniawsky** [comment] 2017-01-21 13:03
@csmosx 

> It fixed the "No PostCSS Config found" error I couldn't figure out.

🤣  I was searching for it for weeks...

> I'm currently asking why and if thats the final behavior, if so I will update the docs soon.
> I'm interested in that too.

A gentle :shipit: on webpack/webpack#4073 👍 to get rid of the { ident: 'crap' } 😛

**Comment by andrebautista** [comment] 2017-04-17 03:01
Pulling my hair out over why this doesn't seem to run the autoprefixer plugin.  Trying to debug the loader also but documentation is pretty poor around how to do that.  Any advice would be greatly appreciated, I've scoured the autoprefixer, postcss, and extract text issue boards to find a solution and this is the closest I've come.
```
{
                test: /\.less$/,
                use: ExtractTextPlugin.extract({
                    fallback: "style-loader",
                    use: [
                        {
                            loader: "css-loader"
                        },
                        {
                            loader: "postcss-loader",
                            options: {
                                plugins: function() {
                                    return [
                                        require('precss'), //tried with and without this
                                        require("autoprefixer")
                                    ];
                                }
                            }
                        },
                        {
                            loader: "less-loader"
                        }
                    ]
                })
            }
```

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:06
```diff
- require("autoprefixer")
+ require("autoprefixer")({...options})
```

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:06
webpack >= v2.2.1

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:08
`precss` is unmaintained and if you use Less then you don't need it, since it's propose is to mimic SASS

**Comment by andrebautista** [comment] 2017-04-17 03:14
@michael-ciniawsky 2.4.1.  Are options required?  I previously had this plugin on webpack 1.x and I thought it was working with no values being passed in.

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:17
```
 require("autoprefixer")() // defaults
```

Should also work, otherwise the bug is somewhere else 😛

**Comment by andrebautista** [comment] 2017-04-17 03:24
Hmm no dice there.  Here's some of my build, I see nothing about autoprefixer (line 8) but then again I'm not sure if I should.
```
       [0] ./src/images/globals/sprite-checkbox-radio.svg 1.71 kB {0} [built]
       [1] ./~/less-loader/stringify.loader.js!./src/less/core/fcGlobals.less 1.37 kB [built]
       [2] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [3] ./~/less-loader/stringify.loader.js!./src/less/core/assets.less 421 bytes [built]
       [4] ./~/css-loader!./~/remodal/dist/remodal-default-theme.css 5.97 kB {0} [built]
       [5] ./~/css-loader!./~/remodal/dist/remodal.css 1.84 kB {0} [built]
       [6] ./src/images/site_images/abc/img_intro-mbl.jpg 20.3 kB {0} [built]
       [7] ./src/images/site_images/abc/img_intro.jpg 70.1 kB {0} [built]
       [8] ./~/css-loader!./~/postcss-loader?{}!./~/less-loader!./src/less/main.less 37.6 kB {0} [built]
       [9] ./~/less-loader/stringify.loader.js!./src/less/core/buttons.less 588 bytes [built]
      [10] ./~/less-loader/stringify.loader.js!./src/less/core/colors.less 565 bytes [built]
      [11] ./~/less-loader/stringify.loader.js!./src/less/core/typography.less 913 bytes [built]
      [13] ./~/less-loader/stringify.loader.js!./src/less/layout/modal.less 2.82 kB [built]
      [14] ./~/less-loader/stringify.loader.js!./src/less/pages/intro.less 1.45 kB [built]
      [23] ./~/less-loader/stringify.loader.js!./src/less/widgets/quizStatusBar.less 1.6 kB [built]```

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:27
That look wierd, could you post the full log please

**Comment by andrebautista** [comment] 2017-04-17 03:30
Like so?
```
Webpack is watching the files…

(node:134) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
Hash: 6c762d33e4e6256bbfd9
Version: webpack 2.4.1
Time: 2941ms
                 Asset      Size  Chunks                    Chunk Names
     abcJeanius.js    526 kB       0  [emitted]  [big]  abcJeanius
      abcEvents.js    313 kB       1  [emitted]  [big]  abcEvents
    abcLauncher.js   15.1 kB       2  [emitted]         abcLauncher
    abcJeanius.css    141 kB       0  [emitted]         abcJeanius
 abcJeanius.js.map    649 kB       0  [emitted]         abcJeanius
abcJeanius.css.map  95 bytes       0  [emitted]         abcJeanius
  abcEvents.js.map    406 kB       1  [emitted]         abcEvents
abcLauncher.js.map   17.8 kB       2  [emitted]         abcLauncher
   [0] ./src/js/site_configs/ag/dev/agUrls.dev.js 373 bytes {0} {1} {2} [built]
   [1] ./~/jquery/dist/jquery.js 268 kB {0} {1} [built]
   [2] ./src/js/events/events.js 7.13 kB {0} {1} [built]
   [3] ./src/js/site_configs/ag/agCore.config.js 1.85 kB {0} {1} {2} [built]
   [6] ./src/js/core/menu.js 9.2 kB {0} [built]
  [10] ./src/js/site_configs/ag/agEvents.js 12.9 kB {0} {1} [built]
  [11] ./src/js/site_configs/ag/agPage.js 2.29 kB {0} {1} [built]
  [13] ./src/js/badges/fcBadges.js 8.16 kB {0} [built]
  [14] ./src/js/core/user.js 1.63 kB {0} {2} [built]
  [17] ./src/less/main.less 41 bytes {0} [built]
  [18] ./src/js/core/init.js 1.56 kB {0} [built]
  [19] ./src/js/quiz/quiz.js 5.27 kB {0} [built]
  [44] ./src/js/abcEvents.js 393 bytes {1} [built]
  [45] ./src/js/abcJeanius.js 3.5 kB {0} [built]
  [47] ./src/js/site_configs/ag/dev/agLauncher.dev.js 8.22 kB {2} [built]
    + 61 hidden modules
Child extract-text-webpack-plugin:
       [0] ./src/images/globals/sprite-checkbox-radio.svg 1.71 kB {0} [built]
       [1] ./~/less-loader/stringify.loader.js!./src/less/core/fcGlobals.less 1.37 kB [built]
       [2] ./~/css-loader/lib/css-base.js 1.51 kB {0} [built]
       [3] ./~/less-loader/stringify.loader.js!./src/less/core/assets.less 421 bytes [built]
       [4] ./~/css-loader!./~/remodal/dist/remodal-default-theme.css 5.97 kB {0} [built]
       [5] ./~/css-loader!./~/remodal/dist/remodal.css 1.84 kB {0} [built]
       [6] ./src/images/site_images/ag/ag_img_intro-mbl.jpg 20.3 kB {0} [built]
       [7] ./src/images/site_images/ag/ag_img_intro.jpg 70.1 kB {0} [built]
       [8] ./~/css-loader!./~/postcss-loader?{}!./~/less-loader!./src/less/main.less 37.6 kB {0} [built]
       [9] ./~/less-loader/stringify.loader.js!./src/less/core/buttons.less 588 bytes [built]
      [10] ./~/less-loader/stringify.loader.js!./src/less/core/colors.less 565 bytes [built]
      [11] ./~/less-loader/stringify.loader.js!./src/less/core/typography.less 913 bytes [built]
      [13] ./~/less-loader/stringify.loader.js!./src/less/layout/modal.less 2.82 kB [built]
      [14] ./~/less-loader/stringify.loader.js!./src/less/pages/intro.less 1.45 kB [built]
      [23] ./~/less-loader/stringify.loader.js!./src/less/widgets/quizStatusBar.less 1.6 kB [built]
        + 9 hidden modules```

**Comment by michael-ciniawsky** [comment] 2017-04-17 03:37
```
 [8] ./~/css-loader!./~/postcss-loader?{}!./~/less-loader!./src/less/main.less 37.6 kB {0} [built]
```
```
./~/css-loader!./~/postcss-loader?{ /* Plugins? */ }!./~/less-loader
```

Which versions of webpack, ETWP && loaders you are running on atm ?

**Comment by andrebautista** [comment] 2017-04-17 03:44
webpack:  2.4.1
less-loader: 2.2.3
ETWP: 2.1.0
autoprefixer: 6.7.7

**Comment by michael-ciniawsky** [comment] 2017-04-17 04:15
`css-loader/postcss-loader`? :)

**Comment by andrebautista** [comment] 2017-04-17 04:18
Oh of course, how could I forget that one 😝 
postcss-loader: 0.13.0

**Comment by michael-ciniawsky** [comment] 2017-04-17 04:25
You will need postcss-loader > v1.0.0 for webpack v2 compatibility, this should also remove

```
(node:134) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

please make sure to have the **latest** `style-loader/css-loader` aswell
