### ISSUE TITLE
[2.0.6] `www.` is stripped from domains

### ISSUE THREAD

**Issue by janslu** [postcss/postcss-loader#267] opened 2017-06-27 22:02 UTC
I'm using postcss-loader with webpack3 and sass-loader and adding this block causes the absolute address used for font loading to be stripped of www. prefix:

```
{
    loader: "postcss-loader",
    options: {
        plugins: function () {
            return [
                require('autoprefixer')('last 2 versions', 'ie 11'),
                require('cssnano')(_{normalizeUrl: {stripWWW: false}}_)
            ]
        },
        sourceMap: false
    }
},
```
I tried adding the option to cssnano hoping this will help, but even removing cssnano from plugins and leaving only autoprefixer causes the same effect. This option for cssnano also doesn't help... Any idea what I'm doing wrong?

**Comment by michael-ciniawsky** [comment] 2017-06-27 22:16
Normally `postcss-loader` doesn't mess with paths by default, it is just a wrapper for  `postcss` and the rest is done via plugins. Could you show the 'full' relevant part `rule > test.scss` of `webpack.config.js` and maybe setup a small test repo? ⚠️ Note that `css-loader` uses `cssnano` aswell internally

**Comment by janslu** [comment] 2017-06-27 22:23
Of course! Here's the whole scss block. The address remains ok (with www.)  if I remove either  loader: "postcss-loader" block or both plugins from  loader: "postcss-loader" > plugins array... 
```
{
    test: /\.scss$/,
    loader: ExtractTextPlugin.extract({
        fallback: 'style-loader',
        use: [
            {
                loader: "css-loader",
                options: {
                    sourceMap: false,
                    modules: false,
                    importLoaders: true
                }
            },
            {
                loader: "postcss-loader",
                options: {
                    plugins: function () {
                        return [
                            require('autoprefixer')('last 2 versions', 'ie 11'),
                            require('cssnano')({normalizeUrl: {stripWWW: false}})
                        ]
                    },
                    sourceMap: false
                }
            },
            {
                loader: "sass-loader",
                options: {
                    sourceMap: false,
                    includePaths: ["node_modules/foundation-sites/scss", "node_modules/motion-ui"]
                }
            }
        ]
    })
},
```

**Comment by janslu** [comment] 2017-06-29 09:21
Sorry to bother you. I lack the knowledge to dig deeper and find the reason, but here's some more information, maybe you will be able to find the culprit... 

I found a config that works for me, but it seems to be patching something that shouldn't need patching... 

1. code being changed - www. is being stripped from font-face declaration:

```
@font-face{font-family:bb-icons;src:url(https://www.babyboom.pl/fonts/bb-icons/bb-icons.svg#bb-icons) format("svg"),url(https://www.babyboom.pl/fonts/bb-icons/bb-icons.ttf) format("truetype"),url(https://www.babyboom.pl/fonts/bb-icons/bb-icons.eot) format("eot"),url(https://www.babyboom.pl/fonts/bb-icons/bb-icons.woff2) format("woff2"),url(https://www.babyboom.pl/fonts/bb-icons/bb-icons.woff) format("woff")}
```

I have stripped options and require from above scss test, so I have only:
```
{
      loader: "postcss-loader"
},
```

and my postcss.config.js is:

```
module.exports = {
  plugins: {
    'autoprefixer': { browsers: ['last 2 versions', 'ie 11'] },
    'cssnano': {normalizeUrl: {stripWWW: false}},
    'postcss-urlrewrite': {
      imports: true,
      properties: true,
      rules: [
          { from: '//babyboom.pl', to: '//www.babyboom.pl' }
      ]
    }
  },
}
```

this url rewrite is necessary but not enough, I also need to disable:

```
//new webpack.LoaderOptionsPlugin({
   //    minimize: true
//}),
```
and this configuration works fine. 

Just to make sure - even running "empty" postcss with no other plugins removes the www. Therefore I have to have the 'postcss-urlrewrite' plugin enabled. But then having LoaderOptionsPlugin minimize enabled, removes the www (again?)... This option doesn't seem to make any difference at the moment, so I can live with that. I just hate not knowing what's really going on...

**Comment by michael-ciniawsky** [comment] 2017-06-29 20:27
I take a look into it soon :)

**Comment by michael-ciniawsky** [comment] 2017-07-03 07:36
It's recommend to use the `cssnano` implementation in `css-loader` via `options.minimize` for the time being, since `css-loader` rewrites `url()` by default to resolve assets 'the webpack way'. Just remove `cssnano` from `postcss.config.js`. The `@font-face` issue is likely to be caused by `css-loader` aswell, bc of how it handles assets resolving `url()`. You could set `options.url = false` to disable this behaviour in `css-laoder` **completely**, but this affects all `url()`'s then 🙃. I recommend to include fonts via `<link href="path/to/fonts.css">` in `index.html` instead (e.g via/like Google Fonts). Also `postcss-urlrewrite` seems to be unnecessary  and can be removed aswell, I personally never had the need for plugins like that, when using `webpack`

**Closed by michael-ciniawsky** 2017-07-03 07:36 UTC
Labels: question, type: bug
