### ISSUE TITLE
Unnecessary curly bracket

### ISSUE THREAD

**Issue by bifunctor** [postcss/postcss-loader#364] opened 2018-05-27 17:35 UTC
Hi all 

I am trying to use `postloader`rwith webpack 4 as following:
```

   test: /\.scss$/,
    use: [
      {
        loader: "css-loader"
      },
      {
        loader: "postcss-loader"
      },
      {
        loader: "sass-loader",
        options: {
          sourceMap: true,
          includePaths: ["node_modules", "node_modules/@material/*"].map(
            d => path.join(__dirname, d)
          )
        }
      }
    ]
  },

```  

I have to include node_modules, because of https://github.com/material-components/material-components-web

The` index.scss` file contains:

```
body {
  margin: 0;
  padding: 0;
}

```
The compiler complains:

```
ERROR in ./src/index.scss
Module build failed: Syntax Error

(1:6) Unnecessary curly bracket

> 1 | body {
    |      ^
  2 |   margin: 0;
  3 |   padding: 0; } 

```
Thanks

**Comment by evilebottnawi** [comment] 2018-05-28 10:55
@bifunctor looks you have invalid configuration and `scss` doesn't compile to css. Can you create minimum reproducible test repo?

**Comment by bifunctor** [comment] 2018-05-28 20:01
That is the whole configuration:

```
const HtmlWebPackPlugin = require("html-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const MiniCssExtractPlugin = require("mini-css-extract-plugin");
const path = require("path");
const glob = require("glob");


module.exports = {
  entry: ["./src/index.js"],
  output: {
    path: path.resolve(__dirname, "dist"),
    filename: "bundle.[hash].js"
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: "babel-loader",
          options: {
            presets: ["@babel/preset-env", "@babel/preset-react"]
          }
        }
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: "html-loader",
            options: {
              minimize: true
            }
          }
        ]
      },
      {
        test: /\.scss$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader
          },
          {
            loader: "css-loader"
          },
          /*{
            loader: "postcss-loader"
          },*/
          {
            loader: "sass-loader",
            options: {
              sourceMap: true,
              includePaths: ["node_modules", "node_modules/@material/*", "src"].map(
                d => path.join(__dirname, d)
              )
            }
          }
        ]
      },
      {
        test: /\.(woff(2)?|ttf|eot|svg)(\?v=\d+\.\d+\.\d+)?$/,
        use: [
          {
            loader: "file-loader",
            options: {
              name: "[name][hash].[ext]",
              outputPath: "fonts/"
            }
          }
        ]
      }
    ]
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: "./public/index.html",
      filename: "./index.html"
    }),
    new CopyWebpackPlugin([
      {
        from: "public"
      }
    ])
  ]
};
``` 

Hope it helps.

THanks

**Comment by evilebottnawi** [comment] 2018-05-29 16:59
@bifunctor it is syntax error, you have invalid `scss` or `css`, please create minimum reproducible test repo. Also in future use `gitter` or `stackoverflow`

**Comment by evilebottnawi** [comment] 2018-06-01 18:46
@bifunctor problem still exists?

**Comment by bifunctor** [comment] 2018-06-02 22:31
Yes, I will create an example and will post it. 

Thanks

**Comment by michael-ciniawsky** [comment] 2018-07-09 10:38
As this seems to be an `{Error}` with your code somwhere I'm closing this for now. But in case you still have an issue and provide a minimal repro I will reopen the issue

**Closed by michael-ciniawsky** 2018-07-09 10:38 UTC
